#!/bin/bash
# Manual test script for Phase 4B - Join & Lobby Screens
# Tests the complete join flow with actual API integration

set -e

echo "=== Phase 4B Testing: Join & Lobby Screens ==="
echo ""

# Check if API server is running
echo "1. Checking API server..."
if ! curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health | grep -q "200"; then
  echo "   ✗ API server not running on port 3000"
  echo "   Start it with: npm run dev --workspace=@quizzquizz/api-server"
  exit 1
fi
echo "   ✓ API server is running"

# Check if player app is running
echo ""
echo "2. Checking player app server..."
if ! curl -s -o /dev/null -w "%{http_code}" http://localhost:3002 | grep -q "200"; then
  echo "   ✗ Player app not running on port 3002"
  echo "   Start it with: npm run dev --workspace=@quizzquizz/player-app"
  exit 1
fi
echo "   ✓ Player app server is running"

# Run unit tests
echo ""
echo "3. Running component unit tests..."
cd /workspaces/quizzquizz
npm test -- --run --workspace=@quizzquizz/player-app 2>&1 | grep -E "(PASS|FAIL|Test|✓|✗)" || true

echo ""
echo "=== Automated Tests Complete ===" 
echo ""
echo "=== Manual Testing Required ==="
echo ""
echo "Follow these steps to test the join flow:"
echo ""
echo "SETUP:"
echo "  1. Open http://localhost:3002 in a browser"
echo "  2. Open http://localhost:3000 API in another tab (for creating session)"
echo ""
echo "TEST 1: Create a session via API"
echo "  curl -X POST http://localhost:3000/api/sessions \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"questionBankId\":\"sample-general-knowledge\"}' | jq"
echo ""
echo "  Expected: Returns sessionId, pin, hostToken"
echo "  Note the PIN (e.g., 123456)"
echo ""
echo "TEST 2: Join Screen Validation"
echo "  a) In player app, verify Join Quiz screen appears"
echo "  b) Try submitting empty PIN → should show error"
echo "  c) Try submitting 5 digits → should show error"
echo "  d) Try submitting letters → should be blocked"
echo "  e) Enter valid 6-digit PIN → should navigate to nickname screen"
echo ""
echo "TEST 3: Nickname Screen Validation"
echo "  a) Verify PIN is displayed at top"
echo "  b) Try submitting empty nickname → should show error"
echo "  c) Try submitting 21+ characters → should be blocked at 20"
echo "  d) Click 'Change PIN' → should go back to join screen"
echo "  e) Enter valid nickname and submit"
echo ""
echo "TEST 4: API Integration"
echo "  a) With invalid PIN (999999):"
echo "     Enter PIN 999999 → nickname 'TestPlayer'"
echo "     Expected: Error 'Quiz not found'"
echo ""
echo "  b) With valid PIN:"
echo "     Enter correct PIN → nickname 'Player1'"
echo "     Expected: Navigate to lobby screen"
echo ""
echo "TEST 5: Lobby Screen"
echo "  a) Verify 'Playing as: Player1' is shown"
echo "  b) Verify 'Waiting for host to start...' message"
echo "  c) Verify player count shows '1 player(s) joined'"
echo "  d) Open second browser window/tab"
echo "  e) Join with same PIN, nickname 'Player2'"
echo "  f) Verify first lobby updates to '2 player(s) joined'"
echo "  g) Click 'Leave Quiz' → should return to join screen"
echo ""
echo "TEST 6: Session Start Detection"
echo "  a) Join session with Player1"
echo "  b) Start session via API:"
echo "     curl -X POST http://localhost:3000/api/sessions/SESSION_ID/start \\"
echo "       -H 'Authorization: Bearer HOST_TOKEN'"
echo "  c) Lobby should detect game started and navigate to play screen"
echo "  d) Verify placeholder 'Question Screen' appears"
echo ""  
echo "TEST 7: Session Deletion Detection"
echo "  a) Join session with Player1"
echo "  b) Delete session via API:"
echo "     curl -X DELETE http://localhost:3000/api/sessions/SESSION_ID \\"
echo "       -H 'Authorization: Bearer HOST_TOKEN'"
echo "  c) Lobby should show 'Quiz was cancelled' and redirect to join"
echo ""
echo "TEST 8: LocalStorage Persistence"
echo "  a) Join session and reach lobby"
echo "  b) Refresh browser (F5)"
echo "  c) Should restore state and return to lobby"
echo "  d) Click 'Leave Quiz'"
echo "  e) Refresh browser"
echo "  f) Should show join screen (state cleared)"
echo ""
echo "TEST 9: Multiple Players Concurrent"
echo "  a) Open 3-5 browser windows/tabs"
echo "  b) Join all with same PIN, different nicknames"
echo "  c) Verify all lobbies show correct player count"
echo "  d) Start session via API"
echo "  e) Verify all players navigate to play screen"
echo ""
echo "TEST 10: Error Handling"
echo "  a) Turn off WiFi/disconnect network"
echo "  b) Try to submit nickname"
echo "  c) Should show 'Network error' message"
echo "  d) Reconnect network"
echo "  e) Try again → should work"
echo ""
echo "=== Phase 4B Testing Complete ==="
echo ""
echo "If all tests pass: Phase 4B is ready! ✅"
echo "Next: Phase 4C - Question & Answer Screens"
