import { getPrisma } from '../db/index.js';
import { auth } from './config.js';

/**
 * Bootstraps a global admin user on server startup.
 *
 * Reads ADMIN_EMAIL from env. If no admin user exists in the DB yet, creates one
 * using ADMIN_PASSWORD (or a random 16-char password if not set), sets
 * mustChangePassword=true, and logs the credentials to stdout.
 */
export async function bootstrapAdminUser(): Promise<void> {
  const adminEmail = process.env.ADMIN_EMAIL;

  if (!adminEmail) {
    return; // ADMIN_EMAIL not configured — skip seeding
  }

  const prisma = getPrisma();

  // Check if any admin already exists
  const existingAdmin = await prisma.user.findFirst({
    where: { isAdmin: true },
    select: { id: true, email: true },
  });

  if (existingAdmin) {
    console.log(`✓ Admin user already exists: ${existingAdmin.email}`);
    return;
  }

  // Determine password
  const providedPassword = process.env.ADMIN_PASSWORD;
  const password = providedPassword ?? generateRandomPassword();
  const autoGenerated = !providedPassword;

  // Create the admin user via Better Auth (handles password hashing)
  let userId: string;
  try {
    const usernameBase = adminEmail.split('@')[0]!.replace(/[^a-zA-Z0-9_]/g, '_');
    const username = usernameBase || 'admin';

    const result = await auth.api.signUpEmail({
      body: {
        email: adminEmail,
        password,
        name: 'Admin',
        username,
      },
    });

    if (!result?.user?.id) {
      throw new Error('Better Auth sign-up did not return a user ID');
    }
    userId = result.user.id;
  } catch (err) {
    // User might already exist (e.g. was created without admin flag)
    const existing = await prisma.user.findUnique({
      where: { email: adminEmail },
      select: { id: true },
    });
    if (!existing) {
      console.error('❌ Failed to create admin user:', err);
      return;
    }
    userId = existing.id;
  }

  // Promote to admin and flag for password reset
  await prisma.user.update({
    where: { id: userId },
    data: { isAdmin: true, mustChangePassword: true },
  });

  console.log('');
  console.log('╔══════════════════════════════════════════════════╗');
  console.log('║         🔐  ADMIN USER CREATED                   ║');
  console.log('╠══════════════════════════════════════════════════╣');
  console.log(`║  Email   : ${adminEmail.padEnd(38)}║`);
  console.log(`║  Password: ${password.padEnd(38)}║`);
  if (autoGenerated) {
    console.log('║  ⚠ Password was auto-generated — save it now!   ║');
  }
  console.log('║  A password reset is required on first login.    ║');
  console.log('╚══════════════════════════════════════════════════╝');
  console.log('');
}

function generateRandomPassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%';
  let result = '';
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  for (const byte of array) {
    result += chars[byte % chars.length];
  }
  return result;
}
